namespace MLIR.Generators.Emitters;

using System;
using System.Collections.Generic;
using System.Text;
using MLIR.ODS.Model;

internal sealed class DialectEmitter
{
    private readonly DialectSymbolResolver resolver;
    private readonly StringBuilder builder = new();
    private readonly Dictionary<string, OperationBodySyntaxMetadata> bodySyntaxMetadataByOperation = new(StringComparer.Ordinal);

    public DialectEmitter(DialectSymbolResolver resolver)
    {
        this.resolver = resolver;
    }

    public string Generate(DialectModel dialect)
    {
        var dialectClassName = DialectGeneratorNaming.GetDialectRegistrationClassName(dialect);

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace " + DialectGeneratorNaming.GetGeneratedNamespace(dialect) + ";");
        builder.AppendLine();
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using System.Linq;");
        builder.AppendLine("using MLIR.Dialects;");
        builder.AppendLine("using MLIR.Semantics;");
        builder.AppendLine("using MLIR.Syntax;");
        builder.AppendLine("using MLIR.Text;");
        builder.AppendLine("using MLIR.Transforms;");
        builder.AppendLine();

        foreach (var operation in dialect.Operations)
        {
            OperationEmitter.Emit(builder, operation);
            builder.AppendLine();

            if (operation.AssemblyFormat != null)
            {
                var metadata = OperationBodySyntaxEmitter.Emit(builder, operation);
                bodySyntaxMetadataByOperation[DialectGeneratorNaming.GetOperationClassName(operation)] = metadata;
                builder.AppendLine();

                AssemblyFormatEmitter.Emit(builder, operation, metadata, resolver);
                builder.AppendLine();
            }
        }

        foreach (var attribute in dialect.Attributes)
        {
            AttributeEmitter.Emit(builder, attribute);
            builder.AppendLine();
        }

        foreach (var type in dialect.Types)
        {
            TypeEmitter.Emit(builder, type);
            builder.AppendLine();
        }

        EmitterHelpers.AppendXmlDocComment(builder, dialect.Summary, dialect.Description);
        builder.AppendLine("public static class " + dialectClassName);
        builder.AppendLine("{");
        builder.AppendLine("    public static Dialect Create()");
        builder.AppendLine("    {");
        builder.AppendLine("        return Dialect.Create(\"" + dialect.Name + "\", dialect =>");
        builder.AppendLine("        {");

        foreach (var operation in dialect.Operations)
        {
            AppendOperationRegistration(operation);
        }

        foreach (var attribute in dialect.Attributes)
        {
            builder.AppendLine("            dialect.AddAttribute(" + DialectGeneratorNaming.GetAttributeClassName(attribute) + ".AttributeDefinition);");
        }

        foreach (var type in dialect.Types)
        {
            builder.AppendLine("            dialect.AddType(" + DialectGeneratorNaming.GetTypeClassName(type) + ".TypeDefinition);");
        }

        builder.AppendLine("        });");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private void AppendOperationRegistration(OperationModel operation)
    {
        builder.AppendLine("            dialect.AddOperation(" + DialectGeneratorNaming.GetOperationClassName(operation) + ".OperationDefinition);");
    }
}
