namespace MLIR.Generators.Emitters;

using System.Text;
using MLIR.ODS.Model;

internal static class DialectFileEmitter
{
    public static void EmitHeader(StringBuilder builder, DialectModel dialect)
    {
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("#pragma warning disable 1591");
        builder.AppendLine();
        builder.AppendLine("namespace " + DialectGeneratorNaming.GetGeneratedNamespace(dialect) + ";");
        builder.AppendLine();
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using System.Linq;");
        builder.AppendLine("using System.Numerics;");
        builder.AppendLine("using MLIR.Dialects;");
        builder.AppendLine("using MLIR.Dialects.Attributes;");
        builder.AppendLine("using MLIR.Dialects.Attributes.Collections;");
        builder.AppendLine("using MLIR.Dialects.Attributes.Primitives;");
        builder.AppendLine("using MLIR.Semantics;");
        builder.AppendLine("using MLIR.Semantics.Attributes;");
        builder.AppendLine("using MLIR.Semantics.Attributes.Collections;");
        builder.AppendLine("using MLIR.Semantics.Attributes.Primitives;");
        builder.AppendLine("using MLIR.Semantics.Types.Collections;");
        builder.AppendLine("using MLIR.Semantics.Types.Primitives;");
        builder.AppendLine("using MLIR.Syntax;");
        builder.AppendLine("using MLIR.Syntax.Attributes;");
        builder.AppendLine("using MLIR.Syntax.Attributes.Collections;");
        builder.AppendLine("using MLIR.Syntax.Attributes.Primitives;");
        builder.AppendLine("using MLIR.Syntax.Types.Collections;");
        builder.AppendLine("using MLIR.Syntax.Types.Primitives;");
        builder.AppendLine("using MLIR.Text;");
        builder.AppendLine("using MLIR.Transforms;");
        builder.AppendLine();
    }
}
