namespace MLIR.Generators.Emitters;

using System;
using System.Collections.Generic;
using System.Text;
using MLIR.ODS.Model;

internal sealed class DialectEmitter
{
    private readonly StringBuilder builder = new();
    private readonly Dictionary<string, OperationBodySyntaxMetadata> bodySyntaxMetadataByOperation = new(StringComparer.Ordinal);

    public string Generate(DialectModel dialect)
    {
        var dialectClassName = DialectGeneratorNaming.GetDialectRegistrationClassName(dialect);

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace " + DialectGeneratorNaming.GetGeneratedNamespace(dialect) + ";");
        builder.AppendLine();
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using MLIR.Dialects;");
        builder.AppendLine("using MLIR.Semantics;");
        builder.AppendLine("using MLIR.Syntax;");
        builder.AppendLine("using MLIR.Text;");
        builder.AppendLine("using MLIR.Transforms;");
        builder.AppendLine();

        foreach (var operation in dialect.Operations)
        {
            OperationEmitter.Emit(builder, operation);
            builder.AppendLine();

            if (operation.AssemblyFormat != null)
            {
                var metadata = OperationBodySyntaxEmitter.Emit(builder, operation);
                bodySyntaxMetadataByOperation[DialectGeneratorNaming.GetOperationClassName(operation)] = metadata;
                builder.AppendLine();

                AssemblyFormatEmitter.Emit(builder, operation);
                builder.AppendLine();
            }
        }

        foreach (var attribute in dialect.Attributes)
        {
            AttributeEmitter.Emit(builder, attribute);
            builder.AppendLine();
        }

        foreach (var type in dialect.Types)
        {
            TypeEmitter.Emit(builder, type);
            builder.AppendLine();
        }

        EmitterHelpers.AppendXmlDocComment(builder, dialect.Summary, dialect.Description);
        builder.AppendLine("public static class " + dialectClassName);
        builder.AppendLine("{");
        builder.AppendLine("    public static Dialect Create()");
        builder.AppendLine("    {");
        builder.AppendLine("        return Dialect.Create(\"" + dialect.Name + "\", dialect =>");
        builder.AppendLine("        {");

        foreach (var operation in dialect.Operations)
        {
            AppendOperationRegistration(operation);
        }

        foreach (var attribute in dialect.Attributes)
        {
            var attributeClassName = DialectGeneratorNaming.GetAttributeClassName(attribute);
            builder.AppendLine(
                "            dialect.AddAttribute(new AttributeDefinition(\"" + attribute.Name + "\", factory: static context => new " + attributeClassName + "(context)));");
        }

        foreach (var type in dialect.Types)
        {
            var typeClassName = DialectGeneratorNaming.GetTypeClassName(type);
            builder.AppendLine(
                "            dialect.AddType(new TypeDefinition(\"" + type.Name + "\", factory: static context => new " + typeClassName + "(context)));");
        }

        builder.AppendLine("        });");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private void AppendOperationRegistration(OperationModel operation)
    {
        var operationClassName = DialectGeneratorNaming.GetOperationClassName(operation);
        builder.AppendLine("            dialect.AddOperation(\"" + operation.Name + "\", operation =>");
        builder.AppendLine("            {");
        foreach (var operand in operation.Operands)
        {
            builder.AppendLine("                operation.Operand(\"" + operand + "\");");
        }

        foreach (var result in operation.Results)
        {
            builder.AppendLine("                operation.Result(\"" + result + "\");");
        }

        foreach (var attribute in operation.Attributes)
        {
            builder.AppendLine("                operation.OptionalAttribute(\"" + attribute + "\");");
        }

        builder.AppendLine("                operation.WithFactory(static context => new " + operationClassName + "(context));");
        if (operation.HasCustomAssemblyFormat)
        {
            builder.AppendLine("                operation.WithAssemblyFormat(new " + operationClassName + "AssemblyFormat());");
        }

        builder.AppendLine("            });");
    }
}
