namespace MLIR.Generators;

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using MLIR.ODS.Model;
using MLIR.ODS.Model.AssemblyFormat;
using MLIR.Text;

internal static class DialectSourceEmitter
{
    public static string GenerateDialectSource(DialectModel dialect)
    {
        return new Emitter().Generate(dialect);
    }

    private sealed class Emitter
    {
        private readonly StringBuilder builder = new();
        private readonly Dictionary<string, OperationBodySyntaxMetadata> bodySyntaxMetadataByOperation = new(StringComparer.Ordinal);

        public string Generate(DialectModel dialect)
        {
            var dialectClassName = DialectGeneratorNaming.GetDialectRegistrationClassName(dialect);

            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("#nullable enable");
            builder.AppendLine();
            builder.AppendLine("namespace " + DialectGeneratorNaming.GetGeneratedNamespace(dialect) + ";");
            builder.AppendLine();
            builder.AppendLine("using System.Collections.Generic;");
            builder.AppendLine("using MLIR.Dialects;");
            builder.AppendLine("using MLIR.Semantics;");
            builder.AppendLine("using MLIR.Syntax;");
            builder.AppendLine("using MLIR.Text;");
            builder.AppendLine("using MLIR.Transforms;");
            builder.AppendLine();

            foreach (var operation in dialect.Operations)
            {
                AppendOperationClass(operation);
                builder.AppendLine();

                if (operation.AssemblyFormat != null)
                {
                    AppendOperationBodySyntaxClass(operation);
                    builder.AppendLine();
                }

                if (operation.HasCustomAssemblyFormat)
                {
                    AppendAssemblyFormatClass(operation);
                    builder.AppendLine();
                }
            }

            foreach (var attribute in dialect.Attributes)
            {
                AppendAttributeClass(attribute);
                builder.AppendLine();
            }

            foreach (var type in dialect.Types)
            {
                AppendTypeClass(type);
                builder.AppendLine();
            }

            AppendXmlDocComment(dialect.Summary, dialect.Description);
            builder.AppendLine("public static class " + dialectClassName);
            builder.AppendLine("{");
            builder.AppendLine("    public static Dialect Create()");
            builder.AppendLine("    {");
            builder.AppendLine("        return Dialect.Create(\"" + dialect.Name + "\", dialect =>");
            builder.AppendLine("        {");

            foreach (var operation in dialect.Operations)
            {
                AppendOperationRegistration(operation);
            }

            foreach (var attribute in dialect.Attributes)
            {
                var attributeClassName = DialectGeneratorNaming.GetAttributeClassName(attribute);
                builder.AppendLine(
                    "            dialect.AddAttribute(new AttributeDefinition(\"" + attribute.Name + "\", factory: static context => new " + attributeClassName + "(context)));");
            }

            foreach (var type in dialect.Types)
            {
                var typeClassName = DialectGeneratorNaming.GetTypeClassName(type);
                builder.AppendLine(
                    "            dialect.AddType(new TypeDefinition(\"" + type.Name + "\", factory: static context => new " + typeClassName + "(context)));");
            }

            builder.AppendLine("        });");
            builder.AppendLine("    }");
            builder.AppendLine("}");

            return builder.ToString();
        }

        private void AppendOperationRegistration(OperationModel operation)
        {
            var operationClassName = DialectGeneratorNaming.GetOperationClassName(operation);
            builder.AppendLine("            dialect.AddOperation(\"" + operation.Name + "\", operation =>");
            builder.AppendLine("            {");
            foreach (var operand in operation.Operands)
            {
                builder.AppendLine("                operation.Operand(\"" + operand + "\");");
            }

            foreach (var result in operation.Results)
            {
                builder.AppendLine("                operation.Result(\"" + result + "\");");
            }

            foreach (var attribute in operation.Attributes)
            {
                builder.AppendLine("                operation.OptionalAttribute(\"" + attribute + "\");");
            }

            builder.AppendLine("                operation.WithFactory(static context => new " + operationClassName + "(context));");
            if (operation.HasCustomAssemblyFormat)
            {
                builder.AppendLine("                operation.WithAssemblyFormat(new " + operationClassName + "AssemblyFormat());");
            }

            builder.AppendLine("            });");
        }

        private void AppendOperationClass(OperationModel operation)
        {
            var className = DialectGeneratorNaming.GetOperationClassName(operation);
            var resultReferenceName = operation.Results.Count == 1 ? "ResultValue" : null;

            AppendXmlDocComment(operation.Summary, operation.Description);
            builder.AppendLine("public sealed class " + className + " : Operation");
            builder.AppendLine("{");
            builder.AppendLine("    private readonly IReadOnlyList<Region> regions;");
            builder.AppendLine("    private readonly IReadOnlyList<NamedAttribute> attributes;");
            builder.AppendLine("    private readonly TypeReference? typeSignatureReference;");
            builder.AppendLine("    private readonly IReadOnlyList<ValueReference> resultValues;");
            builder.AppendLine("    private readonly IReadOnlyList<ValueReference> operandValues;");
            builder.AppendLine("    private readonly IReadOnlyList<BlockReference> successorReferences;");
            builder.AppendLine();
            builder.AppendLine("    public " + className + "(OperationConstructionContext context)");
            builder.AppendLine("        : base(context.Syntax, context.Name, context.Definition)");
            builder.AppendLine("    {");
            builder.AppendLine("        regions = context.Regions;");
            builder.AppendLine("        attributes = context.Attributes;");
            builder.AppendLine("        typeSignatureReference = context.TypeSignatureReference;");
            builder.AppendLine("        resultValues = context.ResultValues;");
            builder.AppendLine("        operandValues = context.OperandValues;");
            builder.AppendLine("        successorReferences = context.SuccessorReferences;");
            builder.AppendLine("    }");
            builder.AppendLine();
            builder.AppendLine("    public override IReadOnlyList<Region> Regions => regions;");
            builder.AppendLine("    public override IReadOnlyList<NamedAttribute> Attributes => attributes;");
            builder.AppendLine("    public override TypeReference? TypeSignatureReference => typeSignatureReference;");
            builder.AppendLine("    public override IReadOnlyList<ValueReference> ResultValues => resultValues;");
            builder.AppendLine("    public override IReadOnlyList<ValueReference> OperandValues => operandValues;");
            builder.AppendLine("    public override IReadOnlyList<BlockReference> SuccessorReferences => successorReferences;");
            builder.AppendLine();

            for (var i = 0; i < operation.Operands.Count; i++)
            {
                builder.AppendLine(
                    "    public ValueReference " + DialectGeneratorNaming.ToPascalCase(operation.Operands[i]) + " => OperandValues[" + i.ToString(CultureInfo.InvariantCulture) + "];");
            }

            for (var i = 0; i < operation.Results.Count; i++)
            {
                var propertyName = operation.Results.Count == 1
                    ? "ResultValue"
                    : DialectGeneratorNaming.ToPascalCase(operation.Results[i]);
                builder.AppendLine(
                    "    public ValueReference " + propertyName + " => ResultValues[" + i.ToString(CultureInfo.InvariantCulture) + "];");
            }

            if (resultReferenceName != null && operation.Results[0] != "result")
            {
                builder.AppendLine(
                    "    public ValueReference " + DialectGeneratorNaming.ToPascalCase(operation.Results[0]) + " => " + resultReferenceName + ";");
            }

            builder.AppendLine("}");
        }

        private void AppendOperationBodySyntaxClass(OperationModel operation)
        {
            var className = DialectGeneratorNaming.GetOperationClassName(operation);
            var assemblyFormat = operation.AssemblyFormat!;
            var metadata = ComputeBodySyntaxMetadata(operation, assemblyFormat, className);
            bodySyntaxMetadataByOperation[className] = metadata;
            var fields = metadata.Fields;

            builder.AppendLine("public sealed class " + className + "BodySyntax : OperationBodySyntax");
            builder.AppendLine("{");

            builder.Append("    public " + className + "BodySyntax(");
            for (var i = 0; i < fields.Count; i++)
            {
                if (i > 0)
                {
                    builder.Append(", ");
                }

                builder.Append(fields[i].CsType + " " + LowerFirst(fields[i].Name));
            }

            builder.AppendLine(")");
            builder.AppendLine("    {");
            foreach (var field in fields)
            {
                builder.AppendLine("        " + field.Name + " = " + LowerFirst(field.Name) + ";");
            }

            builder.AppendLine("    }");

            if (fields.Count > 0)
            {
                builder.AppendLine();
                foreach (var field in fields)
                {
                    builder.AppendLine("    public " + field.CsType + " " + field.Name + " { get; }");
                }
            }

            builder.AppendLine();
            builder.AppendLine("    public override void WriteTo(Text.SyntaxWriter writer, int indentLevel)");
            builder.AppendLine("    {");
            foreach (var field in fields)
            {
                builder.Append(field.WriteToCode);
            }

            builder.AppendLine("    }");
            builder.AppendLine("}");
        }

        private OperationBodySyntaxMetadata ComputeBodySyntaxMetadata(OperationModel operation, AssemblyFormatModel assemblyFormat, string operationClassName)
        {
            var metadata = new OperationBodySyntaxMetadata(operationClassName);
            var usedNames = new HashSet<string>(StringComparer.Ordinal);

            foreach (var element in assemblyFormat.Elements)
            {
                AppendBodySyntaxFields(usedNames, element, operation, metadata);
            }

            return metadata;
        }

        private void AppendAssemblyFormatClass(OperationModel operation)
        {
            var className = DialectGeneratorNaming.GetOperationClassName(operation);
            builder.AppendLine("public sealed class " + className + "AssemblyFormat : IOperationAssemblyFormat");
            builder.AppendLine("{");
            builder.AppendLine("    public bool TryParse(SyntaxToken nameToken, IReadOnlyList<SyntaxToken> resultTokens, IReadOnlyList<SyntaxToken> resultCommaTokens, SyntaxToken? equalsToken, OperationParsingContext context, out OperationBodySyntax? body)");
            builder.AppendLine("    {");
            builder.AppendLine("        body = null;");
            builder.AppendLine("        return false;");
            builder.AppendLine("    }");
            builder.AppendLine();
            builder.AppendLine("    public Operation Bind(OperationSyntax syntax, OperationDefinition definition, Binder binder)");
            builder.AppendLine("    {");
            builder.AppendLine("        var body = (" + className + "BodySyntax)syntax.Body;");
            builder.AppendLine("        binder.Report(new AssemblyDiagnostic(syntax.Location, $\"Custom assembly bodies are not yet supported for '{definition.Name}'.\"));");
            builder.AppendLine("        return new UnknownOperation(");
            builder.AppendLine("            syntax,");
            builder.AppendLine("            definition.Name,");
            builder.AppendLine("            definition,");
            builder.AppendLine("            new List<Region>(),");
            builder.AppendLine("            new List<NamedAttribute>(),");
            builder.AppendLine("            null,");
            builder.AppendLine("            new List<ValueReference>(),");
            builder.AppendLine("            new List<ValueReference>(),");
            builder.AppendLine("            new List<BlockReference>());");
            builder.AppendLine("    }");
            builder.AppendLine();
            builder.AppendLine("    public OperationSyntax BuildCustomAssemblySyntax(Operation operation, ConcreteSyntaxBuilderContext context)");
            builder.AppendLine("    {");
            builder.AppendLine("        return context.RewriteOperation(operation, context.TransformGenericBody(operation));");
            builder.AppendLine("    }");
            builder.AppendLine("}");
        }

        private void AppendAttributeClass(AttributeModel attribute)
        {
            var className = DialectGeneratorNaming.GetAttributeClassName(attribute);
            builder.AppendLine("public sealed class " + className + " : AttributeValue");
            builder.AppendLine("{");
            builder.AppendLine("    public " + className + "(AttributeValueConstructionContext context)");
            builder.AppendLine("        : base(context.Syntax, context.Name, context.Definition, context.Location)");
            builder.AppendLine("    {");
            builder.AppendLine("    }");
            builder.AppendLine("}");
        }

        private void AppendTypeClass(TypeModel type)
        {
            var className = DialectGeneratorNaming.GetTypeClassName(type);
            builder.AppendLine("public sealed class " + className + " : TypeReference");
            builder.AppendLine("{");
            builder.AppendLine("    public " + className + "(TypeReferenceConstructionContext context)");
            builder.AppendLine("        : base(context.Syntax, context.Name, context.Definition, context.Location)");
            builder.AppendLine("    {");
            builder.AppendLine("    }");
            builder.AppendLine("}");
        }

        private void AppendXmlDocComment(string? summary, string? description)
        {
            if (!string.IsNullOrWhiteSpace(summary))
            {
                builder.AppendLine("/// <summary>" + EscapeXmlText(summary!.Trim()) + "</summary>");
            }

            if (!string.IsNullOrWhiteSpace(description))
            {
                builder.AppendLine("/// <remarks>");
                var trimmedDescription = description!.Trim();
                foreach (var rawLine in trimmedDescription.Split('\n'))
                {
                    builder.AppendLine("/// " + EscapeXmlText(rawLine.TrimEnd('\r')));
                }

                builder.AppendLine("/// </remarks>");
            }
        }
    }

    private static void AppendBodySyntaxFields(HashSet<string> usedNames, Element element, OperationModel operation, OperationBodySyntaxMetadata metadata)
    {
        switch (element)
        {
            case LiteralChunk literal:
                foreach (var lit in literal.Value)
                {
                    switch (lit)
                    {
                        case PunctuationLiteral punc:
                        {
                            var name = MakeUnique(GetPunctuationFieldName(punc.TokenKind), usedNames);
                            var field = new BodySyntaxField(name, "SyntaxToken",
                                "        writer.WriteToken(" + name + ", string.Empty);\n");
                            metadata.AddField(field);
                            metadata.AddComponentField(new BodyComponentField(BodyComponentKind.Literal, "Punctuation:" + punc.TokenKind, field.Name));
                            break;
                        }

                        case KeywordLiteral kw:
                        {
                            var name = MakeUnique(DialectGeneratorNaming.ToPascalCase(kw.Spelling) + "Keyword", usedNames);
                            var field = new BodySyntaxField(name, "SyntaxToken",
                                "        writer.WriteToken(" + name + ", \" \");\n");
                            metadata.AddField(field);
                            metadata.AddComponentField(new BodyComponentField(BodyComponentKind.Literal, "Keyword:" + kw.Spelling, field.Name));
                            break;
                        }

                        // WhitespaceLiteral, NewlineLiteral, EmptyLiteral → no field; spacing is in stored trivia
                    }
                }

                break;

            case VariableChunk variable:
            {
                var pascalName = DialectGeneratorNaming.ToPascalCase(variable.Name);
                if (ContainsName(operation.Attributes, variable.Name))
                {
                    var name = MakeUnique(pascalName, usedNames);
                    var field = new BodySyntaxField(name, "AttributeValueSyntax",
                        "        " + name + ".WriteTo(writer, \" \");\n");
                    metadata.AddField(field);
                    metadata.AddComponentField(new BodyComponentField(BodyComponentKind.Attribute, variable.Name, field.Name));
                }
                else
                {
                    // Operand, result variable, or unknown → SyntaxToken
                    var name = MakeUnique(pascalName, usedNames);
                    var field = new BodySyntaxField(name, "SyntaxToken",
                        "        writer.WriteToken(" + name + ", \" \");\n");
                    metadata.AddField(field);
                    metadata.AddComponentField(new BodyComponentField(
                        GetComponentKindForVariable(operation, variable.Name),
                        variable.Name,
                        field.Name));
                }

                break;
            }

            case AttrDictDirectiveChunk _:
            {
                var name = MakeUnique("AttrDict", usedNames);
                var field = new BodySyntaxField(name, "DelimitedSyntaxList<NamedAttributeSyntax>",
                    GenerateDelimitedNamedAttributeWriteTo(name));
                metadata.AddField(field);
                metadata.AddComponentField(new BodyComponentField(BodyComponentKind.AttrDict, "AttrDict", field.Name));
                break;
            }

            case AttrDictWithKeywordDirectiveChunk _:
            {
                var name = MakeUnique("AttrDictWithKeyword", usedNames);
                var field = new BodySyntaxField(name, "DelimitedSyntaxList<NamedAttributeSyntax>",
                    GenerateDelimitedNamedAttributeWriteTo(name));
                metadata.AddField(field);
                metadata.AddComponentField(new BodyComponentField(BodyComponentKind.AttrDictWithKeyword, "AttrDictWithKeyword", field.Name));
                break;
            }

            case PropDictDirectiveChunk _:
            {
                var name = MakeUnique("PropDict", usedNames);
                var field = new BodySyntaxField(name, "DelimitedSyntaxList<NamedAttributeSyntax>",
                    GenerateDelimitedNamedAttributeWriteTo(name));
                metadata.AddField(field);
                metadata.AddComponentField(new BodyComponentField(BodyComponentKind.PropDict, "PropDict", field.Name));
                break;
            }

            case RegionsDirectiveChunk _:
            {
                var name = MakeUnique("Regions", usedNames);
                var field = new BodySyntaxField(name, "IReadOnlyList<RegionSyntax>",
                    "        foreach (var region in " + name + ")\n" +
                    "        {\n" +
                    "            writeRegion(writer, region, indentLevel);\n" +
                    "        }\n");
                metadata.AddField(field);
                metadata.AddComponentField(new BodyComponentField(BodyComponentKind.Regions, "Regions", field.Name));
                break;
            }

            case TypeDirectiveChunk typeDir:
            {
                var baseName = typeDir.Operand is VariableOperand varOp
                    ? DialectGeneratorNaming.ToPascalCase(varOp.Name) + "Type"
                    : "Type";
                var name = MakeUnique(baseName, usedNames);
                var field = new BodySyntaxField(name, "TypeSyntax",
                    "        " + name + ".WriteTo(writer, \" \");\n");
                metadata.AddField(field);
                metadata.AddComponentField(new BodyComponentField(BodyComponentKind.Type, GetDirectiveOperandName(typeDir.Operand), field.Name));
                break;
            }

            case SuccessorsDirectiveChunk _:
            {
                var name = MakeUnique("Successors", usedNames);
                var field = new BodySyntaxField(name, "DelimitedSyntaxList<SyntaxToken>",
                    GenerateDelimitedTokenWriteTo(name));
                metadata.AddField(field);
                metadata.AddComponentField(new BodyComponentField(BodyComponentKind.Successors, "Successors", field.Name));
                break;
            }

            case OperandsDirectiveChunk _:
            {
                var name = MakeUnique("Operands", usedNames);
                var field = new BodySyntaxField(name, "DelimitedSyntaxList<SyntaxToken>",
                    GenerateDelimitedTokenWriteTo(name));
                metadata.AddField(field);
                metadata.AddComponentField(new BodyComponentField(BodyComponentKind.Operands, "Operands", field.Name));
                break;
            }

            // OptionalGroup, OilistDirectiveChunk, CustomDirectiveChunk, FunctionalTypeDirectiveChunk,
            // QualifiedDirectiveChunk, RefDirectiveChunk, ResultsDirectiveChunk → not stored in this CST class
        }
    }

    private static string GenerateDelimitedNamedAttributeWriteTo(string fieldName)
    {
        return "        writer.WriteDelimitedList(" + fieldName + ", \" \");\n";
    }

    private static string GenerateDelimitedTokenWriteTo(string fieldName)
    {
        return "        writer.WriteDelimitedList(" + fieldName + ", \" \");\n";
    }

    private static string GetPunctuationFieldName(TokenKind tokenKind)
    {
        return tokenKind switch
        {
            TokenKind.Comma => "CommaToken",
            TokenKind.LParen => "LParenToken",
            TokenKind.RParen => "RParenToken",
            TokenKind.LBracket => "LBracketToken",
            TokenKind.RBracket => "RBracketToken",
            TokenKind.LBrace => "LBraceToken",
            TokenKind.RBrace => "RBraceToken",
            TokenKind.Arrow => "ArrowToken",
            TokenKind.Colon => "ColonToken",
            TokenKind.Equal => "EqualToken",
            TokenKind.LessThan => "LessThanToken",
            TokenKind.GreaterThan => "GreaterThanToken",
            TokenKind.Question => "QuestionToken",
            TokenKind.Star => "StarToken",
            TokenKind.Plus => "PlusToken",
            TokenKind.Minus => "MinusToken",
            TokenKind.Dot => "DotToken",
            TokenKind.At => "AtToken",
            TokenKind.Hash => "HashToken",
            _ => "Token",
        };
    }

    private static string MakeUnique(string baseName, HashSet<string> used)
    {
        if (used.Add(baseName))
        {
            return baseName;
        }

        for (var i = 2; ; i++)
        {
            var candidate = baseName + i.ToString(CultureInfo.InvariantCulture);
            if (used.Add(candidate))
            {
                return candidate;
            }
        }
    }

    private static string LowerFirst(string name)
    {
        if (name.Length == 0)
        {
            return name;
        }

        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }

    private static bool ContainsName(IReadOnlyList<string> names, string name)
    {
        foreach (var n in names)
        {
            if (string.Equals(n, name, StringComparison.Ordinal))
            {
                return true;
            }
        }

        return false;
    }

    private static BodyComponentKind GetComponentKindForVariable(OperationModel operation, string variableName)
    {
        if (ContainsName(operation.Results, variableName))
        {
            return BodyComponentKind.Result;
        }

        if (ContainsName(operation.Operands, variableName))
        {
            return BodyComponentKind.Operand;
        }

        return BodyComponentKind.Unknown;
    }

    private static string GetDirectiveOperandName(DirectiveOperand operand)
    {
        return operand switch
        {
            VariableOperand variable => variable.Name,
            _ => operand?.GetType().Name ?? "Operand"
        };
    }

    private static string EscapeXmlText(string text)
    {
        return text
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;");
    }

    private sealed class BodySyntaxField
    {
        public BodySyntaxField(string name, string csType, string writeToCode)
        {
            Name = name;
            CsType = csType;
            WriteToCode = writeToCode;
        }

        public string Name { get; }
        public string CsType { get; }

        /// <summary>
        /// C# code (indented for the WriteTo body, ending with a newline) that writes this field.
        /// </summary>
        public string WriteToCode { get; }
    }

    private sealed class BodyComponentField
    {
        public BodyComponentField(BodyComponentKind kind, string componentName, string fieldName)
        {
            Kind = kind;
            ComponentName = componentName;
            FieldName = fieldName;
        }

        public BodyComponentKind Kind { get; }

        public string ComponentName { get; }

        public string FieldName { get; }
    }

    private enum BodyComponentKind
    {
        Literal,
        Attribute,
        Operand,
        Result,
        AttrDict,
        AttrDictWithKeyword,
        PropDict,
        Regions,
        Type,
        Successors,
        Operands,
        Unknown
    }

    private sealed class OperationBodySyntaxMetadata
    {
        private readonly List<BodySyntaxField> fields = new();
        private readonly List<BodyComponentField> componentFields = new();

        public OperationBodySyntaxMetadata(string operationClassName)
        {
            OperationClassName = operationClassName;
        }

        public string OperationClassName { get; }

        public string BodyClassName => OperationClassName + "BodySyntax";

        public IReadOnlyList<BodySyntaxField> Fields => fields;

        public IReadOnlyList<BodyComponentField> ComponentFields => componentFields;

        public void AddField(BodySyntaxField field) => fields.Add(field);

        public void AddComponentField(BodyComponentField componentField) => componentFields.Add(componentField);
    }
}
