<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>MLIR.Generators</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <IsRoslynComponent>true</IsRoslynComponent>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <OutputItemType>Analyzer</OutputItemType>
    <NoWarn>$(NoWarn);RS2008</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.11.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MLIR.ODS\MLIR.ODS.csproj" />
    <ProjectReference Include="..\MLIR\MLIR.csproj" />
    <ProjectReference Include="..\TableGen\TableGen.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Prelude\Include\**\*.td" LogicalName="Include/%(RecursiveDir)%(Filename)%(Extension)" />
    <EmbeddedResource Include="Prelude\Upstream\**\*.td" LogicalName="Upstream/%(RecursiveDir)%(Filename)%(Extension)" />
    <EmbeddedResource Include="Prelude\Extensions\**\*.td" LogicalName="Extensions/%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
