namespace MLIR.Generators;

using System.Globalization;
using System.Text;
using MLIR.ODS.Model;

internal static class OdsDialectSourceEmitter
{
    public static string GenerateDialectSource(OdsDialectModel dialect)
    {
        var builder = new StringBuilder();
        var dialectClassName = OdsDialectGeneratorNaming.GetDialectRegistrationClassName(dialect);

        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace " + OdsDialectGeneratorNaming.GetGeneratedNamespace(dialect) + ";");
        builder.AppendLine();
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using MLIR.Dialects;");
        builder.AppendLine("using MLIR.Semantics;");
        builder.AppendLine("using MLIR.Syntax;");
        builder.AppendLine("using MLIR.Text;");
        builder.AppendLine("using MLIR.Transforms;");
        builder.AppendLine();

        foreach (var operation in dialect.Operations)
        {
            AppendOperationClass(builder, operation);
            builder.AppendLine();

            if (operation.HasCustomAssemblyFormat)
            {
                AppendAssemblyFormatClass(builder, operation);
                builder.AppendLine();
            }
        }

        foreach (var attribute in dialect.Attributes)
        {
            AppendAttributeClass(builder, attribute);
            builder.AppendLine();
        }

        foreach (var type in dialect.Types)
        {
            AppendTypeClass(builder, type);
            builder.AppendLine();
        }

        builder.AppendLine("public static class " + dialectClassName);
        builder.AppendLine("{");
        builder.AppendLine("    public static Dialect Create()");
        builder.AppendLine("    {");
        builder.AppendLine("        return Dialect.Create(\"" + dialect.Name + "\", dialect =>");
        builder.AppendLine("        {");

        foreach (var operation in dialect.Operations)
        {
            AppendOperationRegistration(builder, operation);
        }

        foreach (var attribute in dialect.Attributes)
        {
            var attributeClassName = OdsDialectGeneratorNaming.GetAttributeClassName(attribute);
            builder.AppendLine(
                "            dialect.AddAttribute(new AttributeDefinition(\"" + attribute.Name + "\", factory: static context => new " + attributeClassName + "(context)));");
        }

        foreach (var type in dialect.Types)
        {
            var typeClassName = OdsDialectGeneratorNaming.GetTypeClassName(type);
            builder.AppendLine(
                "            dialect.AddType(new TypeDefinition(\"" + type.Name + "\", factory: static context => new " + typeClassName + "(context)));");
        }

        builder.AppendLine("        });");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static void AppendOperationRegistration(StringBuilder builder, OdsOperationModel operation)
    {
        var operationClassName = OdsDialectGeneratorNaming.GetOperationClassName(operation);
        builder.AppendLine("            dialect.AddOperation(\"" + operation.Name + "\", operation =>");
        builder.AppendLine("            {");
        foreach (var operand in operation.Operands)
        {
            builder.AppendLine("                operation.Operand(\"" + operand + "\");");
        }

        foreach (var result in operation.Results)
        {
            builder.AppendLine("                operation.Result(\"" + result + "\");");
        }

        foreach (var attribute in operation.Attributes)
        {
            builder.AppendLine("                operation.OptionalAttribute(\"" + attribute + "\");");
        }

        builder.AppendLine("                operation.WithFactory(static context => new " + operationClassName + "(context));");
        if (operation.HasCustomAssemblyFormat)
        {
            builder.AppendLine("                operation.WithAssemblyFormat(new " + operationClassName + "AssemblyFormat());");
        }

        builder.AppendLine("            });");
    }

    private static void AppendOperationClass(StringBuilder builder, OdsOperationModel operation)
    {
        var className = OdsDialectGeneratorNaming.GetOperationClassName(operation);
        var resultReferenceName = operation.Results.Count == 1 ? "ResultValue" : null;

        builder.AppendLine("public sealed class " + className + " : Operation");
        builder.AppendLine("{");
        builder.AppendLine("    private readonly IReadOnlyList<Region> regions;");
        builder.AppendLine("    private readonly IReadOnlyList<NamedAttribute> attributes;");
        builder.AppendLine("    private readonly TypeReference? typeSignatureReference;");
        builder.AppendLine("    private readonly IReadOnlyList<ValueReference> resultValues;");
        builder.AppendLine("    private readonly IReadOnlyList<ValueReference> operandValues;");
        builder.AppendLine("    private readonly IReadOnlyList<BlockReference> successorReferences;");
        builder.AppendLine();
        builder.AppendLine("    public " + className + "(OperationConstructionContext context)");
        builder.AppendLine("        : base(context.Syntax, context.Name, context.Definition)");
        builder.AppendLine("    {");
        builder.AppendLine("        regions = context.Regions;");
        builder.AppendLine("        attributes = context.Attributes;");
        builder.AppendLine("        typeSignatureReference = context.TypeSignatureReference;");
        builder.AppendLine("        resultValues = context.ResultValues;");
        builder.AppendLine("        operandValues = context.OperandValues;");
        builder.AppendLine("        successorReferences = context.SuccessorReferences;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public override IReadOnlyList<Region> Regions => regions;");
        builder.AppendLine("    public override IReadOnlyList<NamedAttribute> Attributes => attributes;");
        builder.AppendLine("    public override TypeReference? TypeSignatureReference => typeSignatureReference;");
        builder.AppendLine("    public override IReadOnlyList<ValueReference> ResultValues => resultValues;");
        builder.AppendLine("    public override IReadOnlyList<ValueReference> OperandValues => operandValues;");
        builder.AppendLine("    public override IReadOnlyList<BlockReference> SuccessorReferences => successorReferences;");
        builder.AppendLine();

        for (var i = 0; i < operation.Operands.Count; i++)
        {
            builder.AppendLine(
                "    public ValueReference " + OdsDialectGeneratorNaming.ToPascalCase(operation.Operands[i]) + " => OperandValues[" + i.ToString(CultureInfo.InvariantCulture) + "];");
        }

        for (var i = 0; i < operation.Results.Count; i++)
        {
            var propertyName = operation.Results.Count == 1
                ? "ResultValue"
                : OdsDialectGeneratorNaming.ToPascalCase(operation.Results[i]);
            builder.AppendLine(
                "    public ValueReference " + propertyName + " => ResultValues[" + i.ToString(CultureInfo.InvariantCulture) + "];");
        }

        if (resultReferenceName != null && operation.Results[0] != "result")
        {
            builder.AppendLine(
                "    public ValueReference " + OdsDialectGeneratorNaming.ToPascalCase(operation.Results[0]) + " => " + resultReferenceName + ";");
        }

        builder.AppendLine("}");
    }

    private static void AppendAssemblyFormatClass(StringBuilder builder, OdsOperationModel operation)
    {
        var className = OdsDialectGeneratorNaming.GetOperationClassName(operation);
        builder.AppendLine("public sealed class " + className + "AssemblyFormat : IOperationAssemblyFormat");
        builder.AppendLine("{");
        builder.AppendLine("    public bool TryParse(SyntaxToken nameToken, IReadOnlyList<SyntaxToken> resultTokens, IReadOnlyList<SyntaxToken> resultCommaTokens, SyntaxToken? equalsToken, OperationParsingContext context, out OperationBodySyntax? body)");
        builder.AppendLine("    {");
        builder.AppendLine("        body = null;");
        builder.AppendLine("        return false;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public void Bind(Operation operation, OperationAssemblyBindingContext context)");
        builder.AppendLine("    {");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public OperationSyntax Rewrite(Operation operation, OperationSyntaxTransformContext context)");
        builder.AppendLine("    {");
        builder.AppendLine("        return context.RewriteOperation(operation, context.TransformGenericBody(operation));");
        builder.AppendLine("    }");
        builder.AppendLine("}");
    }

    private static void AppendAttributeClass(StringBuilder builder, OdsAttributeModel attribute)
    {
        var className = OdsDialectGeneratorNaming.GetAttributeClassName(attribute);
        builder.AppendLine("public sealed class " + className + " : AttributeValue");
        builder.AppendLine("{");
        builder.AppendLine("    public " + className + "(AttributeValueConstructionContext context)");
        builder.AppendLine("        : base(context.Syntax, context.Name, context.Definition, context.Location)");
        builder.AppendLine("    {");
        builder.AppendLine("    }");
        builder.AppendLine("}");
    }

    private static void AppendTypeClass(StringBuilder builder, OdsTypeModel type)
    {
        var className = OdsDialectGeneratorNaming.GetTypeClassName(type);
        builder.AppendLine("public sealed class " + className + " : TypeReference");
        builder.AppendLine("{");
        builder.AppendLine("    public " + className + "(TypeReferenceConstructionContext context)");
        builder.AppendLine("        : base(context.Syntax, context.Name, context.Definition, context.Location)");
        builder.AppendLine("    {");
        builder.AppendLine("    }");
        builder.AppendLine("}");
    }
}
